name: post-submit
on:
  push:
    branches:
      - dev
jobs:
  test262test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4
      with:               
                                                                                                                                   submodules: true                                                                           
                              
    - name: Setup JDK                              
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
        cache: sbt

    - name: Setup SBT
      uses: sbt/setup-sbt@v1

    - name: Run test
      env:
        ESMETA_HOME: ${{ github.workspace }}
      run: sbt test262EvalTest
  
  cfg-alert:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
        cache: sbt

    - name: Setup SBT
      uses: sbt/setup-sbt@v1

    - name: Run test
      env:
        ESMETA_HOME: ${{ github.workspace }}
      run: sbt test262EvalTest

    - name: Send a stream message
      uses: zulip/github-actions-zulip/send-message@v1
      with:
        api-key: ${{ secrets.ZULIP_API_KEY }}
        email: "username@example.com"
        organization-url: "https://org.zulipchat.com"
        to: "social"
        type: "stream"
        topic: "Castle"
        content: "I come not, friends, to steal away your hearts."                 